# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/adrybakov/pre-commit-hooks
  rev: 0.2.1
  hooks:
  - id: license-headers
    exclude: 'docs/source/user-guide/library/bravais-lattices/.*/.*.py'
    args:
      - --license-file
      - L-HEADER
      - --update-year
      - --verbose
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.4.2
  hooks:
  - id: black
    language_version: python3.11
