# ================================== LICENSE ===================================
# Wulfric - Cell, Atoms, K-path, visualization.
# Copyright (C) 2023 Andrey Rybakov
#
# e-mail: anry@uv.es, web: adrybakov.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# ================================ END LICENSE =================================


__all__ = ["HS_PLOT_NAMES"]


HS_PLOT_NAMES = {
    R"A": R"A",
    R"A_P": R"A$^{\prime}$",
    R"A0": R"A$_0$",
    R"A0_P": R"A$_0^{\prime}$",
    R"A1": R"A$_1$",
    R"A1_P": R"A$_1^{\prime}$",
    R"B": R"B",
    R"B_P": R"B$^{\prime}$",
    R"B0": R"B$_0$",
    R"B0_P": R"B$_0^{\prime}$",
    R"B1": R"B$_1$",
    R"B1_P": R"B$_1^{\prime}$",
    R"B2": R"B$_2$",
    R"B2_P": R"B$_2^{\prime}$",
    R"C": R"C",
    R"C_P": R"C$^{\prime}$",
    R"C0": R"C$_0$",
    R"C0_P": R"C$_0^{\prime}$",
    R"C1": R"C$_1$",
    R"C1_P": R"C$_1^{\prime}$",
    R"C2": R"C$_2$",
    R"C2_P": R"C$_2^{\prime}$",
    R"C4": R"C$_4$",
    R"C4_P": R"C$_4^{\prime}$",
    R"D": R"D",
    R"D_P": R"D$^{\prime}$",
    R"D0": R"D$_0$",
    R"D0_P": R"D$_0^{\prime}$",
    R"D1": R"D$_1$",
    R"D1_P": R"D$_1^{\prime}$",
    R"D2": R"D$_2$",
    R"D2_P": R"D$_2^{\prime}$",
    R"DELTA0": R"$\Delta_0$",
    R"DELTA0_P": R"$\Delta_0^{\prime}$",
    R"E": R"E",
    R"E_P": R"E$^{\prime}$",
    R"E0": R"E$_0$",
    R"E0_P": R"E$_0^{\prime}$",
    R"E2": R"E$_2$",
    R"E2_P": R"E$_2^{\prime}$",
    R"E4": R"E$_4$",
    R"E4_P": R"E$_4^{\prime}$",
    R"F": R"F",
    R"F_P": R"F$^{\prime}$",
    R"F0": R"F$_0$",
    R"F0_P": R"F$_0^{\prime}$",
    R"F1": R"F$_1$",
    R"F1_P": R"F$_1^{\prime}$",
    R"F2": R"F$_2$",
    R"F2_P": R"F$_2^{\prime}$",
    R"F3": R"F$_4$",
    R"F3_P": R"F$_4^{\prime}$",
    R"F4": R"F$_4$",
    R"F4_P": R"F$_4^{\prime}$",
    R"G": R"G",
    R"G_P": R"G$^{\prime}$",
    R"G0": R"G$_0$",
    R"G0_P": R"G$_0^{\prime}$",
    R"G2": R"G$_2$",
    R"G2_P": R"G$_2^{\prime}$",
    R"G4": R"G$_4$",
    R"G4_P": R"G$_4^{\prime}$",
    R"G6": R"G$_6$",
    R"G6_P": R"G$_6^{\prime}$",
    R"GAMMA": R"$\Gamma$",
    R"GAMMA_P": R"$\Gamma^{\prime}$",
    R"H": R"H",
    R"H_P": R"H$^{\prime}$",
    R"H0": R"H$_0$",
    R"H0_P": R"H$_0^{\prime}$",
    R"H1": R"H$_1$",
    R"H1_P": R"H$_1^{\prime}$",
    R"H2": R"H$_2$",
    R"H2_P": R"H$_2^{\prime}$",
    R"H4": R"H$_4$",
    R"H4_P": R"H$_4^{\prime}$",
    R"H6": R"H$_6$",
    R"H6_P": R"H$_6^{\prime}$",
    R"I": R"I",
    R"I_P": R"I$^{\prime}$",
    R"I1": R"I$_1$",
    R"I1_P": R"I$_1^{\prime}$",
    R"I2": R"I$_2$",
    R"I2_P": R"I$_2^{\prime}$",
    R"J0": R"J$_0$",
    R"J0_P": R"J$_0^{\prime}$",
    R"K": R"K",
    R"K_P": R"K$^{\prime}$",
    R"K2": R"K$_2$",
    R"K2_P": R"K$_2^{\prime}$",
    R"K4": R"K$_4$",
    R"K4_P": R"K$_4^{\prime}$",
    R"L": R"L",
    R"L_P": R"L$^{\prime}$",
    R"L0": R"L$_0$",
    R"L0_P": R"L$_0^{\prime}$",
    R"L1": R"L$_1$",
    R"L1_P": R"L$_1^{\prime}$",
    R"L2": R"L$_2$",
    R"L2_P": R"L$_2^{\prime}$",
    R"L4": R"L$_4$",
    R"L4_P": R"L$_4^{\prime}$",
    R"LAMBDA0": R"$\Lambda_0$",
    R"LAMBDA0_P": R"$\Lambda_0^{\prime}$",
    R"M": R"M",
    R"M_P": R"M$^{\prime}$",
    R"M0": R"M$_0$",
    R"M0_P": R"M$_0^{\prime}$",
    R"M1": R"M$_1$",
    R"M1_P": R"M$_1^{\prime}$",
    R"M2": R"M$_2$",
    R"M2_P": R"M$_2^{\prime}$",
    R"M4": R"M$_4$",
    R"M4_P": R"M$_4^{\prime}$",
    R"M6": R"M$_6$",
    R"M6_P": R"M$_6^{\prime}$",
    R"M8": R"M$_8$",
    R"M8_P": R"M$_8^{\prime}$",
    R"N": R"N",
    R"N_P": R"N$^{\prime}$",
    R"N1": R"N$_1$",
    R"N1_P": R"N$_1^{\prime}$",
    R"N2": R"N$_2$",
    R"N2_P": R"N$_2^{\prime}$",
    R"N4": R"N$_4$",
    R"N4_P": R"N$_4^{\prime}$",
    R"N6": R"N$_6$",
    R"N6_P": R"N$_6^{\prime}$",
    R"P": R"P",
    R"P_P": R"P$^{\prime}$",
    R"P0": R"P$_0$",
    R"P0_P": R"P$_0^{\prime}$",
    R"P1": R"P$_1$",
    R"P1_P": R"P$_1^{\prime}$",
    R"P2": R"P$_2$",
    R"P2_P": R"P$_2^{\prime}$",
    R"Q": R"Q",
    R"Q_P": R"Q$^{\prime}$",
    R"Q0": R"Q$_0$",
    R"Q0_P": R"Q$_0^{\prime}$",
    R"Q1": R"Q$_1$",
    R"Q1_P": R"Q$_1^{\prime}$",
    R"R": R"R",
    R"R_P": R"R$^{\prime}$",
    R"R0": R"R$_0$",
    R"R0_P": R"R$_0^{\prime}$",
    R"R2": R"R$_2$",
    R"R2_P": R"R$_2^{\prime}$",
    R"S": R"S",
    R"S_P": R"S$^{\prime}$",
    R"S0": R"S$_0$",
    R"S0_P": R"S$_0^{\prime}$",
    R"S2": R"S$_2$",
    R"S2_P": R"S$_2^{\prime}$",
    R"S4": R"S$_4$",
    R"S4_P": R"S$_4^{\prime}$",
    R"S6": R"S$_6$",
    R"S6_P": R"S$_6^{\prime}$",
    R"SIGMA": R"$\Sigma$",
    R"SIGMA_P": R"$\Sigma^{\prime}$",
    R"SIGMA0": R"$\Sigma_0$",
    R"SIGMA0_P": R"$\Sigma_0^{\prime}$",
    R"SIGMA1": R"$\Sigma_1$",
    R"SIGMA1_P": R"$\Sigma_1^{\prime}$",
    R"T": R"T",
    R"T_P": R"T$^{\prime}$",
    R"T2": R"T$_2$",
    R"T2_P": R"T$_2^{\prime}$",
    R"U": R"U",
    R"U_P": R"U$^{\prime}$",
    R"U0": R"U$_0$",
    R"U0_P": R"U$_0^{\prime}$",
    R"U2": R"U$_2$",
    R"U2_P": R"U$_2^{\prime}$",
    R"V": R"V",
    R"V_P": R"V$^{\prime}$",
    R"V0": R"V$_0$",
    R"V0_P": R"V$_0^{\prime}$",
    R"V2": R"V$_2$",
    R"V2_P": R"V$_2^{\prime}$",
    R"W": R"W",
    R"W_P": R"W$^{\prime}$",
    R"W2": R"W$_2$",
    R"W2_P": R"W$_2^{\prime}$",
    R"X": R"X",
    R"X_P": R"X$^{\prime}$",
    R"X1": R"X$_1$",
    R"X1_P": R"X$_1^{\prime}$",
    R"X2": R"X$_2$",
    R"X2_P": R"X$_2^{\prime}$",
    R"Y": R"Y",
    R"Y_P": R"Y$^{\prime}$",
    R"Y0": R"Y$_0$",
    R"Y0_P": R"Y$_0^{\prime}$",
    R"Y1": R"Y$_1$",
    R"Y1_P": R"Y$_1^{\prime}$",
    R"Y2": R"Y$_2$",
    R"Y2_P": R"Y$_2^{\prime}$",
    R"Y3": R"Y$_3$",
    R"Y3_P": R"Y$_3^{\prime}$",
    R"Y4": R"Y$_4$",
    R"Y4_P": R"Y$_4^{\prime}$",
    R"Z": R"Z",
    R"Z_P": R"Z$^{\prime}$",
    R"Z0": R"Z$_0$",
    R"Z0_P": R"Z$_0^{\prime}$",
    R"Z1": R"Z$_1$",
    R"Z1_P": R"Z$_1^{\prime}$",
    R"Z2": R"Z$_2$",
    R"Z2_P": R"Z$_2^{\prime}$",
}
