name: Populate kanban with issues

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened


jobs:
  add-to-project:
    name: Add an issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/adrybakov/projects/4
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
