name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    tags:
      - 'v[0-9].*.*'

jobs:
  check-release-metadata:
    name: Check release metadata

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dev tools
      run: pip install gitpython termcolor

    - name: Inspect metadata
      run: python3 -u tools/prepare-release.py -v ${{  github.ref_name }} -rd .

  test:
    name: Unit and documentation tests
    needs:
    - check-release-metadata
    uses: adrybakov/wulfric/.github/workflows/run-tests.yml@main
    with:
      python-version: "3.x"

  build:
    name: Build distribution 📦
    needs:
    - test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/wulfric
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
