name: Test against supported python versions

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches: [ main]

jobs:


  test-310:
    name: (3.10) test
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.10'

  test-311:
    name: (3.11) test
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.11'

  test-312:
    name: (3.12) test
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.12'
  test-313:
    name: (3.13) test
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.13'

  test-314:
    name: (3.14) test
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.14'
