name: Test against supported python versions and operating systems

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches: [main]

jobs:

  single_test:
    name: Run tests on Python 3.12 and ubuntu-latest
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: "3.12"
      os: ubuntu-latest

  python_os_matrix:
    name: Test on Python and OS matrix
    needs: single_test
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: ${{ matrix.python_version }}
      os: ${{ matrix.os }}
    strategy:
      matrix:
        python_version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - python_version: '3.12'
            os: ubuntu-latest
