name: Test against supported python versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-38:
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.8'

  test-39:
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.9'

  test-310:
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.10'

  test-311:
    uses: adrybakov/wulfric/.github/workflows/tests.yml@main
    with:
      python-version: '3.11'
